name: code

on:
  workflow_dispatch: 

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: code
        run: |
          git clone -b dev-next https://github.com/SagerNet/sing-box sing-box
          git clone -b dev-11 https://github.com/White12352/spa spa
          cd sing-box
          #git config user.email "github-actions@github.com"
          #git config user.name "GitHub Actions"
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote -v
          #git remote add new_origin https://github.com/White12352/nias.git
          git remote add new_origin https://github.com/White12352/nias.git
          git remote -v
          git checkout -b sing-box
          #rm -rf .github
          #rm -rf spa
          #cp -r sing-box/* .
          #cp -r sing-box/.github .
          #rm -rf sing-box
          git push --force new_origin sing-box:sing-box
          #git push --force origin --all
          #git push origin --tags
